### ISSUE TITLE
Cannot find module '../webpack/build/webpack.test.conf.js'

### ISSUE THREAD

**Issue by tonyts** [Tarrask/sails-generate-frontend-webpack-vue#1]
If I setup a new project without unit tests and e2e tests, when `sails lift` an error occurred:
_Cannot find module '../webpack/build/webpack.test.conf.js'_

In webpack.js line 55 need to be removed if user didn't setup unit/e2e tests.

**Comment by Tarrask** [comment]
I fixed that with commit 55607fe043cf997ef000bafc6df2d5d40e0b9c89 available on version 0.2.0
